export enum Messages {
  NEW_VIDEO = "NEW_VIDEO",
  NO_SLUG_REDIRECT = "NO_SLUG_REDIRECT",
  NEBULA_REDIRECT = "NEBULA_REDIRECT",
}

export enum Alarms {
  UPDATE_LOOKUP_TABLE = "UPDATE_LOOKUP_TABLE",
}
