// NOTE: These definitions are copies of those in the main TypeScript repo, they should be kept in sync.

/**
 * @type {Object} MatchedVideo
 * @description A matched video object that includes the Nebula video and the Youtube video
 * @property {string} id - The youtube id of the video
 * @property {string} nebulaId - The nebula id of the video
 */
export type MatchedVideo = {
  id: string; // Short youtube id
  slug: string; // Nebula slug
};

/**
 * @type {Object} ChannelEntry
 * @property {string} slug - The channel slug of the channel that the videos belong to
 * @property {string} youtubeId - The youtube id of the channel
 * @property {string} custom_url - The custom url of the channel
 * @property {string[]} matched - A list of youtube video ids that have been matched to a nebula video
 * @property {string[]} not_matched - A list of youtube video ids that have not been matched to a nebula video
 */
export interface ChannelEntry {
  slug: string;
  custom_url: string;
  youtubeId: string;
  matched: MatchedVideo[];
  not_matched: string[];
}

/**
 * @type {Object} LookupTable
 * @description A lookup table that maps youtube video ids to nebula video ids for each known channel. This table is generated by the server and is sent to the client to lookup videos before requesting a redirect from the server.
 * @property {string} generatedAt - The date the lookup table was generated
 * @property {ChannelEntry[]} channels - A list of channel entries {@link ChannelEntry}
 * @property {string} id - The id of the lookup table
 */
export interface LookupTable {
  channels: ChannelEntry[];
  generatedAt: Date;
  id: string;
}
