on:
  pull_request:
  push:
jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # checkout the repo
      - run: yarn install --immutable --immutable-cache --check-cache # install packages
      - run: yarn test:ci # run tests (configured to use jest-junit reporter)

      - name: Test Reporter
        uses: dorny/test-reporter@v1.5.0
        if: success() || failure() # run this step even if previous step failed
        with:
          name: JEST Tests # Name of the check run which will be created
          path: reports/jest-*.xml # Path to test results
          reporter: jest-junit # Format of test results
